// <auto-generated>
// generated using ContentTool. DO NOT EDIT!
// </auto-generated>

using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Collections.ObjectModel;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json;

namespace ContentData
{
    #pragma warning disable
    
    public partial class ArrayMutable
    {
        public string Id { get; set; }
        public IList<double> SingleColumn { get; set; }
        public IList<string> MultiColumn { get; set; }
    }

    public partial class ArrayTableMutable
    {
        public IList<ArrayMutable> ArrayList { get; set; }
    }

    //////////////////////////////
    // readonly class
    //////////////////////////////
    public partial class Array
    {
        public readonly string Id;
        public readonly IReadOnlyList<double> SingleColumn;
        public readonly IReadOnlyList<string> MultiColumn;
        public Array(ArrayMutable data)
        {
            Id = data.Id;
            if(data.SingleColumn != null)
                SingleColumn = data.SingleColumn.ToList().AsReadOnly();
            if(data.MultiColumn != null)
                MultiColumn = data.MultiColumn.ToList().AsReadOnly();
        }
    }

    public partial class ArrayTable
    {
        public readonly IReadOnlyList<Array> ArrayList;
        public ArrayTable(ArrayTableMutable data)
        {
            if(data.ArrayList != null)
                ArrayList = data.ArrayList.Select(x => new Array(x)).ToList().AsReadOnly();
        }
    }

}
