// <auto-generated>
// generated using ContentTool. DO NOT EDIT!
// </auto-generated>

using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Collections.ObjectModel;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json;

namespace ContentData
{
    #pragma warning disable
    
    public partial class SimpleTableMutable
    {
        public IList<SimpleMutable> SimpleList { get; set; }
    }

    //////////////////////////////
    // readonly class
    //////////////////////////////
    public partial class SimpleTable
    {
        public readonly IReadOnlyList<Simple> SimpleList;
        public SimpleTable(SimpleTableMutable data)
        {
            if(data.SimpleList != null)
                SimpleList = data.SimpleList.Select(x => new Simple(x)).ToList().AsReadOnly();
        }
    }

}
