// <auto-generated>
// generated using ContentTool. DO NOT EDIT!
// </auto-generated>

using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Collections.ObjectModel;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json;

namespace ContentData
{
    #pragma warning disable
    
    public partial class SampleMutable
    {
        public string Id { get; set; }
        public string Value1 { get; set; }
        public double Value2 { get; set; }
        public IList<double> Value3 { get; set; }
    }

    public partial class SampleTableMutable
    {
        public IList<SampleMutable> SampleList { get; set; }
    }

    //////////////////////////////
    // readonly class
    //////////////////////////////
    public partial class Sample
    {
        public readonly string Id;
        public readonly string Value1;
        public readonly double Value2;
        public readonly IReadOnlyList<double> Value3;
        public Sample(SampleMutable data)
        {
            Id = data.Id;
            Value1 = data.Value1;
            Value2 = data.Value2;
            if(data.Value3 != null)
                Value3 = data.Value3.ToList().AsReadOnly();
        }
    }

    public partial class SampleTable
    {
        public readonly IReadOnlyList<Sample> SampleList;
        public SampleTable(SampleTableMutable data)
        {
            if(data.SampleList != null)
                SampleList = data.SampleList.Select(x => new Sample(x)).ToList().AsReadOnly();
        }
    }

}
